package constans

const (
	ConfigPath      = "CONFIG_PATH"
	YAML            = "yaml"
	GrpcPort        = "GRPC_PORT"
	PostgresqlPASS  = "PGPASSWORD"
	PGPASSWORD      = "PGPASSWORD"
	PGHOST          = "PGHOST"
	PGUSER          = "PGUSER"
	PGPORT          = "PGPORT"
	RMPASSWORD      = "RMPASSWORD"
	RMHOST          = "RMHOST"
	RMPORT          = "RMPORT"
	RMUSER          = "RMUSER"
	MongoPASS       = "MONGOPASSWORD"
	Topic           = "topic"
	Partition       = "partition"
	Message         = "message"
	WorkerID        = "workerID"
	Offset          = "offset"
	Time            = "time"
	KZ              = "Kz"
	DefaultUserRole = "user"
	AdminRole       = "admin"
	JAEGERHOSTPORT  = "JAEGERHOSTPORT"
	SMSHOST         = "SMSHOST"
	SMSEMAIL        = "SMSEMAIL"
	SMSPASS         = "SMSPASS"
	SMSSMTP         = "SMSSMTP"
)
